apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  labels:
    app: guest-book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: back-end-pod
      app: guest-book-app
  template:
    metadata:
      labels:
        name: back-end-pod
        app: guest-book-app
    spec:
      containers:
        - name: redis-master 
          image: redis
          ports:
          - containerPort: 6379
