apiVersion: v1
kind: Service
metadata:
  name: back-end-service
  labels:
    name: back-end-service
    app: guest-book-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: back-end-pod
    app: guest-book-app